In [1]:
import pandas as pd 
import numpy as np

In [2]:
# map, applymap, getdummies

df = pd.DataFrame({'Name':['Sourav','Komal','Jatin','Anshu','Anurag','Simran','Reema'],
                  'Class':['btech','bca','mca','btech','mcom','mba','bba'],
                  'Rollno':[34,43,11,10,67,89,14]})
df

     Name  Class  Rollno
0  Sourav  btech      34
1   Komal    bca      43
2   Jatin    mca      11
3   Anshu  btech      10
4  Anurag   mcom      67
5  Simran    mba      89
6   Reema    bba      14

In [3]:
df.loc[:,'Class'].str.capitalize()

0    Btech
1      Bca
2      Mca
3    Btech
4     Mcom
5      Mba
6      Bba
Name: Class, dtype: object

In [4]:
df.loc[:,'Rollno'] = df.loc[:,'Rollno']+2
df

     Name  Class  Rollno
0  Sourav  btech      36
1   Komal    bca      45
2   Jatin    mca      13
3   Anshu  btech      12
4  Anurag   mcom      69
5  Simran    mba      91
6   Reema    bba      16

In [5]:
def funcCap(text):
    return text.capitalize()

In [6]:
df.loc[:,'Class'] =  df.loc[:,'Class'].apply(funcCap) #series
df

     Name  Class  Rollno
0  Sourav  Btech      36
1   Komal    Bca      45
2   Jatin    Mca      13
3   Anshu  Btech      12
4  Anurag   Mcom      69
5  Simran    Mba      91
6   Reema    Bba      16

In [7]:
df.map(lambda x: str(x) + ' hi')

        Name     Class Rollno
0  Sourav hi  Btech hi  36 hi
1   Komal hi    Bca hi  45 hi
2   Jatin hi    Mca hi  13 hi
3   Anshu hi  Btech hi  12 hi
4  Anurag hi   Mcom hi  69 hi
5  Simran hi    Mba hi  91 hi
6   Reema hi    Bba hi  16 hi

In [8]:
df.applymap(lambda x: str(x) + ' hi')

C:\Users\manuj\AppData\Local\Temp\ipykernel_10476\3632845601.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: str(x) + ' hi')

        Name     Class Rollno
0  Sourav hi  Btech hi  36 hi
1   Komal hi    Bca hi  45 hi
2   Jatin hi    Mca hi  13 hi
3   Anshu hi  Btech hi  12 hi
4  Anurag hi   Mcom hi  69 hi
5  Simran hi    Mba hi  91 hi
6   Reema hi    Bba hi  16 hi

In [9]:
titanic = pd.read_csv('titanic-dataset.csv')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [10]:
titanic.Survived.value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

In [11]:
titanic.Survived = titanic.Survived.map({0:'Not Survived', 1:'Survived'})
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,Not Survived,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,Survived,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,Not Survived,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,Not Survived,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,Survived,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,Not Survived,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,Survived,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,Not Survived,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,Not Survived,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,Not Survived,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [12]:
pd.get_dummies(titanic.Pclass,dtype = 'int')

     1  2  3
0    0  0  1
1    0  0  1
2    0  1  0
3    0  0  1
4    0  0  1
..  .. .. ..
413  0  0  1
414  1  0  0
415  0  0  1
416  0  0  1
417  0  0  1

[418 rows x 3 columns]

In [13]:
titanic.loc[:,[1,2,3]] = pd.get_dummies(titanic.Pclass, dtype='int')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,1,2,3
0,892,Not Survived,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,0,1
1,893,Survived,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0,0,1
2,894,Not Survived,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,1,0
3,895,Not Survived,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,0,1
4,896,Survived,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,Not Survived,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,0,1
414,1306,Survived,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1,0,0
415,1307,Not Survived,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,0,1
416,1308,Not Survived,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,0,1
417,1309,Not Survived,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0,0,1

In [14]:
titanic.rename(columns={1:'Pclass1',2:'Pclass',3:'Pclass'},inplace=True)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass1,Pclass,Pclass
0,892,Not Survived,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,0,1
1,893,Survived,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0,0,1
2,894,Not Survived,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,1,0
3,895,Not Survived,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,0,1
4,896,Survived,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,Not Survived,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,0,1
414,1306,Survived,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1,0,0
415,1307,Not Survived,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,0,1
416,1308,Not Survived,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,0,1
417,1309,Not Survived,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0,0,1

In [16]:
titanic.shape

(418, 15)