In [1]:
import pandas as pd

In [2]:
# In cmd-- pip install scikit learn -- sklearn 
# In notebook -- !pip install scikit-learn

In [3]:
data = pd.DataFrame({'Result':['good','bad','good','bad','excellent','good','good','excellent']})
data

      Result
0       good
1        bad
2       good
3        bad
4  excellent
5       good
6       good
7  excellent

In [6]:
# data.Result.map({'good':1,'bad':2,'excellent':3})

In [7]:
# label encoder
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [8]:
# fit, transform, fit_transform
encoder.fit(data.Result)

LabelEncoder()

In [9]:
encoder.transform(data.Result)

array([2, 0, 2, 0, 1, 2, 2, 1])

In [10]:
data['Label_result'] = encoder.transform(data.Result)

In [11]:
data

      Result  Label_result
0       good             2
1        bad             0
2       good             2
3        bad             0
4  excellent             1
5       good             2
6       good             2
7  excellent             1

In [12]:
encoder.classes_

array(['bad', 'excellent', 'good'], dtype=object)

In [13]:
encoder.fit_transform(data.Result)

array([2, 0, 2, 0, 1, 2, 2, 1])

In [14]:
df = pd.read_csv('pre-owned cars.csv')

In [15]:
df.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9582 entries, 0 to 9581
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         9582 non-null   object
 1   model         9582 non-null   object
 2   Year          9582 non-null   int64
 3   Age           9582 non-null   int64
 4   kmDriven      9535 non-null   object
 5   Transmission  9582 non-null   object
 6   Owner         9582 non-null   object
 7   FuelType      9582 non-null   object
 8   PostedDate    9582 non-null   object
 9   AdditionInfo  9582 non-null   object
 10  AskPrice      9582 non-null   object
dtypes: int64(2), object(9)
memory usage: 823.6+ KB

In [17]:
df.isnull().sum()

Brand            0
model            0
Year             0
Age              0
kmDriven        47
Transmission     0
Owner            0
FuelType         0
PostedDate       0
AdditionInfo     0
AskPrice         0
dtype: int64

In [18]:
df.columns

Index(['Brand', 'model', 'Year', 'Age', 'kmDriven', 'Transmission', 'Owner',
       'FuelType', 'PostedDate', 'AdditionInfo', 'AskPrice'],
      dtype='object')

In [20]:
df.Transmission.value_counts()

Transmission
Manual       4800
Automatic    4782
Name: count, dtype: int64

In [22]:
le = LabelEncoder()
a = le.fit_transform(df.loc[:,'Transmission'])

In [23]:
df.insert(loc=4, column='trans', value=a)

In [24]:
df

,Brand,model,Year,Age,trans,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,1,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,1,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,1,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,1,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,0,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"
...,...,...,...,...,...,...,...,...,...,...,...,...
9577,Skoda,Octavia,2014,10,0,"105,904 km",Automatic,second,Diesel,Oct-24,"Skoda Octavia 1.9 Elegance TDI, 2014, Diesel","₹ 10,40,000"
9578,Maruti Suzuki,Alto-800,2020,4,1,"55,000 km",Manual,first,Hybrid/CNG,Nov-24,"Maruti Suzuki Alto 800 CNG LXI Optional, 2020,...","₹ 3,75,000"
9579,Maruti Suzuki,Ritz,2013,11,1,"92,000 km",Manual,first,Diesel,Nov-24,"Maruti Suzuki Ritz VDi, 2013, Diesel","₹ 4,15,000"
9580,Hyundai,Verna,2019,5,0,"72,000 km",Automatic,first,Petrol,Oct-24,"Hyundai Verna VTVT 1.6 AT SX Option, 2019, Petrol","₹ 8,55,000"
9581,Hyundai,New i20,2021,3,1,"83,228 km",Manual,second,Petrol,Nov-24,"Hyundai New i20 1.2 Asta IVT, 2021, Petrol","₹ 6,99,000"